[package]
name = "hello"
version = "0.1.0"
authors = ["yu2ta7ka"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m-rt = "0.6.13"
cortex-m-semihosting = "0.3.7"
embedded-hal = "0.2.4"
panic-halt = "0.2.0"
